In [3]:
import torch 
from torch import nn
print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1


In [18]:
print(torch.tensor([[1,2,3],[4,5,6]]).ndim)
Matrix = torch.tensor([[7,8,9],[10,11,12]])
Matrix

2


tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [19]:
Matrix.shape

torch.Size([2, 3])

In [22]:
vec = torch.arange(0,9)
vec.shape

torch.Size([9])

## Intro with Datatypes 
[Pytorch.org tut](https://pytorch.org/tutorials/)


In [28]:
float_32_tensor = torch.tensor([1,2,3], 
                            dtype=torch.float32, # data type, can be altered for different precision and faster computation
                            device='cuda:0', # device to store the tensor, can be 'cpu' or 'cuda:0' for GPU, could be 'cuda:1' for second GPU
                            requires_grad=True # whether to track the gradient of the tensor
                            )
float_32_tensor

tensor([1., 2., 3.], device='cuda:0', requires_grad=True)

## reshaping tensors

In [59]:
vec = torch.arange(0,12)
vec

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
vec.reshape(-1,3) # -1 means the dimension is inferred from the other dimension

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [54]:
vec.reshape(3,-1).shape

torch.Size([3, 3])

In [83]:
vec.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [86]:
vec.reshape(-1,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [84]:
vec.reshape(-1,) 
# -1 means the dimension is inferred from the other dimension

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
vec.reshape(-1,12)
n = 3 
vec.reshape(-1,n) # n has to be a multiple of 12

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [65]:
vec.reshape(-1,1)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])

## Stack

In [105]:
vec_stack = torch.stack([vec, vec, vec], dim=1) 
# dim=0 means stacking along the first dimension
# dim=1 means stacking along the second dimension
print(vec_stack.shape)
vec_stack

torch.Size([12, 3])


tensor([[ 0,  0,  0],
        [ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11]])

In [113]:
vec_2d = vec.reshape(-1,4)
print(vec_2d.ndim)
vec_2d

2


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [121]:
vec_stack_3d = torch.stack([vec_2d, vec_2d, vec_2d], dim=2)
print(vec_stack_3d.shape)
vec_stack_3d

torch.Size([3, 4, 3])


tensor([[[ 0,  0,  0],
         [ 1,  1,  1],
         [ 2,  2,  2],
         [ 3,  3,  3]],

        [[ 4,  4,  4],
         [ 5,  5,  5],
         [ 6,  6,  6],
         [ 7,  7,  7]],

        [[ 8,  8,  8],
         [ 9,  9,  9],
         [10, 10, 10],
         [11, 11, 11]]])

In [129]:
x = torch.arange(0,12)
print(x)
x = x.reshape(1,12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [130]:
x.squeeze() # remove the dimension of size 1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])