In [2]:
import torch
import torch.nn as nn
torch.manual_seed(42)
torch.cuda.manual_seed(42)

## 1. correct Relu Implementation

In [3]:

tensor_test = torch.tensor([[10,15,20,30],[11,21,54,30]], dtype=torch.float32)
tensor_test

linear_layer = nn.Linear(in_features=4, out_features= 5, )
modified_tensor = linear_layer(tensor_test)
print(modified_tensor.shape, tensor_test.shape)
modified_tensor

torch.Size([2, 5]) torch.Size([2, 4])


tensor([[21.2538,  4.3000, 10.2018,  7.7455,  3.7234],
        [20.1435, -3.4807, 23.2180, 16.7184, -3.3840]],
       grad_fn=<AddmmBackward0>)

In [4]:
relu = nn.ReLU()
relu(modified_tensor), relu(modified_tensor).shape

(tensor([[21.2538,  4.3000, 10.2018,  7.7455,  3.7234],
         [20.1435,  0.0000, 23.2180, 16.7184,  0.0000]],
        grad_fn=<ReluBackward0>),
 torch.Size([2, 5]))

In [5]:
relu_linear = nn.ReLU((nn.Linear(in_features=4, out_features=5)))
relu_linear(tensor_test), tensor_test.shape

(tensor([[10., 15., 20., 30.],
         [11., 21., 54., 30.]]),
 torch.Size([2, 4]))

## 2. BCE with/without logits

In [6]:
m = nn.Sigmoid()
loss = nn.BCELoss()
input = torch.tensor([ 2.2082, -0.6380,  0.4617], requires_grad=True)
target = torch.tensor([1, 0, 1], dtype=torch.float32)
print(input, target)
print(m(input))
loss(m(input), target)


tensor([ 2.2082, -0.6380,  0.4617], requires_grad=True) tensor([1., 0., 1.])
tensor([0.9010, 0.3457, 0.6134], grad_fn=<SigmoidBackward0>)


tensor(0.3391, grad_fn=<BinaryCrossEntropyBackward0>)

In [7]:
criterion = nn.BCEWithLogitsLoss()
criterion(input, target)

tensor(0.3391, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)

In [9]:
loss_wo_logits = nn.BCELoss()
loss_w_logits = nn.BCEWithLogitsLoss()
sig = nn.Sigmoid()

with torch.inference_mode():
    input = torch.tensor([2.2082, -0.6380, 0.4617], requires_grad=True)
    target = torch.tensor([1, 0, 1], dtype=torch.float32)

    print(loss_wo_logits(sig(input), target), loss_w_logits(input, target))


tensor(0.3391) tensor(0.3391)


## usually BCE with logits performs better